<?php

namespace Tests\Feature;

use App\Services\BookingSessions\BookingSessionAppartement;
use App\Services\BookingSessions\BookingSessionPaket;
use App\Services\BookingSessions\BookingSessionRouter;
use Tests\TestCase;

class BookingSessionRouterTest extends TestCase {

    public function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     */
    public function it_sets_the_booking_session_by_key() {

        app(BookingSessionRouter::class)->setActiveSession(app(BookingSessionAppartement::class));
        $this->assertEquals(BookingSessionAppartement::class, get_class(booking_session()));

        app(BookingSessionRouter::class)->setActiveSession(app(BookingSessionPaket::class));
        $this->assertEquals(BookingSessionPaket::class, get_class(booking_session()));


    }



}
