title: 'Preisklasse 2: Appartement 2 Raum, OG, Loggien'
klasse: 2
preise:
  hs: '230,00'
  ns: '190,00'
updated_by: bcc7e124-8753-45c4-9127-eacc804b6168
updated_at: 1605707885
blueprint: preise
pauschalen:
  -
    beschreibung: Endreinigung
    preis_pauschale: '189'
preistext: 'Ihr Preis beinhaltet WLAN, sowie Steuern und Servicegebühren.(Kurtaxe entfällt)'
