title: 'Preisklasse Test: Nur für Testzwecke - bitte nicht löschen'
klasse: 99
preise:
  hs: '200,00'
  ns: '100,00'
updated_by: 122fd801-7f34-4b63-aa9f-698c14614ebb
updated_at: 1605290356
blueprint: preise
pauschalen:
  -
    beschreibung: Endreinigung
    preis_pauschale: 100
preistext: 'Preistext'
