title: 'Preisklasse 4: Appartement 3 Raum, EG, Terrasse'
klasse: 4
preise:
  hs: '350,00'
  ns: '310,00'
updated_by: bcc7e124-8753-45c4-9127-eacc804b6168
updated_at: 1607083859
blueprint: preise
pauschalen:
  -
    beschreibung: Endreinigung
    preis_pauschale: 189
preistext: 'Ihr Preis beinhaltet WLAN, sowie Steuern und Servicegebühren.(Kurtaxe entfällt)'
rf: 0
