<?php

namespace Tests\Unit;

use App\Factories\AppartementFactory;
use App\Factories\SaisonFactory;
use App\Models\Appartement;
use App\Repositories\AppartementRepository;
use App\Services\AppartementPriceCalculator;
use App\Services\PriceDisplay;
use Carbon\CarbonPeriod;
use Tests\CreatesModels;
use Tests\SetUpRabatt;
use Tests\TestCase;

class AppartementPricesTest extends TestCase {

    use CreatesModels, SetUpRabatt;

    /**
     * @var mixed|null | Appartement
     */
    protected $appartement = null;

    public function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->appartement = app( AppartementRepository::class )->getByPreisklasse( 'klasse-test' )->first();
    }



    /**
     * @test
     * @dataProvider calcProvider
     */
    public function it_calculates_the_correct_prices( $preisklasse, $hauptsaison, $nights, $expected ) {

        $price = app( AppartementPriceCalculator::class )
            ->input( $this->appartement, $nights, $hauptsaison )
            ->getTotal();

        $this->assertEquals( $expected, $price );

    }


    /**
     * @test
     */
    public function it_can_display_the_correct_prices() {

        $calculator = app( AppartementPriceCalculator::class )->input( $this->appartement, 1 , true );
        $this->appartement->initPricedisplay($calculator);

        $this->assertEquals('200', $this->appartement->pricedisplay()->getCurrentPrice());
    }

    /**
     * @test
     */
    public function it_can_display_the_discount_price() {
        $rabatt = $this->createTestRabatt();
        $calculator = app( AppartementPriceCalculator::class )->input( $this->appartement, 1 , true );
        $this->appartement->initPricedisplay($calculator, $rabatt);
        $this->assertEquals(170 , $this->appartement->pricedisplay()->getCurrentPrice());
        $this->assertEquals('15', $this->appartement->pricedisplay()->getDiscountPercent());
    }




    public function calcProvider() {
        return [
            [ 'klasse-test', true, 1, 200.00 ],
            [ 'klasse-test', false, 1, 100.00],
            [ 'klasse-test', true, 2, 400.00  ],
            [ 'klasse-test', false, 2, 200.00],
        ];
    }





}
