<?php

namespace Tests\Unit;

use Illuminate\Foundation\Testing\Concerns\InteractsWithExceptionHandling;
use Statamic\Assets\Asset;
use Tests\CreatesModels;
use Tests\TestCase;

class EntryModelTest extends TestCase {

    use CreatesModels, InteractsWithExceptionHandling;

    public function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     */
    public function it_gets_slug_of_implicit_statamic_entry() {
        $model = $this->createTestangebot();
        $this->assertEquals('testangebot', $model->slug);
    }

    /**
     * @test
     */
    public function it_gets_the_collection_image() {
        $this->withoutExceptionHandling();
        $model = $this->createGoldfever();
        /**
         * @var $image Asset
         */
        $image = $model->col_img;
        $this->assertEquals(\Statamic\Assets\Asset::class, get_class($image));
    }



}
