<?php

namespace Tests\Unit;

use App\Exceptions\BookingException;
use App\Factories\AngebotFactory;
use App\Factories\AppartementFactory;
use App\Factories\PferdepensionFactory;
use App\Jobs\ProcessAddAngebotToCart;
use App\Jobs\ProcessInitBookingAppartements;
use App\Models\Angebot;
use App\Models\Appartement;
use App\Models\Cart;
use App\Models\Fitness;
use App\Models\Pferdepension;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\Concerns\InteractsWithDatabase;
use Illuminate\Foundation\Testing\Concerns\InteractsWithSession;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\CreatesModels;
use Tests\TestCase;
use Tests\DBSwitcher;

class InitBookingAppartementTest extends TestCase {

    use CreatesModels, RefreshDatabase, InteractsWithSession;


    public function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     */
    public function it_can_init_the_values_for_the_cart() {
        $cart = Cart::create();
        app( ProcessInitBookingAppartements::class, [
            'arrSelection' => [
                'cart'     => $cart,
                'checkin'  => '2020-01-01',
                'checkout' => '2020-01-10',
                'gaeste'   => 3
            ]
        ] )->handle();
        $this->assertEquals( '2020-01-01', cart()->checkin->format( 'Y-m-d' ) );
        $this->assertEquals( '2020-01-10', cart()->checkout->format( 'Y-m-d' ) );
        $this->assertEquals( 3, cart()->gaeste );
    }

}
