<?php

namespace Tests\Unit;

use App\Factories\AngebotFactory;
use App\Factories\PaketFactory;
use App\Models\Angebot;
use App\Repositories\AppartementRepository;
use App\Services\AngebotPriceCalculator;
use App\Services\AppartementPriceCalculator;
use App\Services\PackagePrices;
use App\Services\PaketPriceCalculator;
use Tests\CreatesModels;
use Tests\TestCase;

class PackagePriceTest extends TestCase {


    use CreatesModels;

    public function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     */
    public function it_gets_prices_per_appartementklasse() {
        $model  = $this->createTestpaket();
        $prices = app( PackagePrices::class, [ 'model' => $model ] )->getPrices( 'klasse-5' );
        $this->assertEquals($this->getExpectedData(), $prices->toArray());
    }

    /**
     * @test
     */
    public function it_gets_einzelzimmerzuschlag() {
        $model  = $this->createTestpaket();
        $ez = app( PackagePrices::class, [ 'model' => $model ] )->getPriceEZ( 'klasse-5', true );
        $this->assertEquals(150, $ez);
    }

    protected function getExpectedData() {
        return [
            "klasse"           => "klasse-5",
            "teilnehmer_hs"    => 1000.0,
            "begleitperson_hs" => 800.0,
            "teilnehmer_ns"    => 800.0,
            "begleitperson_ns" => 600.0,
            "type"             => "klasse",
            "enabled"          => true,
            "ez"               => "15"
        ];
    }


}
