<?php

namespace Tests\Unit;

use App\Exceptions\BookingException;
use App\Factories\AppartementFactory;
use App\Models\Appartement;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\Concerns\InteractsWithDatabase;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Statamic\Taxonomies\LocalizedTerm;
use Tests\CreatesModels;
use Tests\TestCase;
use Tests\DBSwitcher;

class PaketTest extends TestCase {

    use DBSwitcher, CreatesModels, DatabaseMigrations, InteractsWithDatabase;

    /**
     * @var \App\Models\Paket|null
     */
    protected $model = null;

    public function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->model = $this->createTestpaket();
    }

    /**
     * @test
     */
    public function it_has_number_of_nights() {
        $this->assertEquals(7, $this->model->nights);
    }

//    /**
//     * @test
//     */
//    public function it_has_maximum_number_of_teilnehmer() {
//        $this->assertEquals(2, $this->model->getMaxTeilnehmer());
//    }
//
//    /**
//     * @test
//     */
//    public function it_has_maximum_number_of_begleitperson() {
//        $this->assertEquals(2, $this->model->getMaxBegleitpersonen());
//    }

    /**
     * @test
     */
    public function it_has_maximum_number_of_bookable_persons() {
        $this->assertEquals(3, $this->model->getMaxBookablePersons());
    }






}
