<?php

namespace Tests\Unit;

use App\Models\Rabatt;
use App\Repositories\RabattRepository;
use Tests\CreatesModels;
use Tests\SetUpRabatt;
use Tests\TestCase;

class RabattRepositoryTest extends TestCase {

    use CreatesModels, SetUpRabatt;

    public function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->setUpRabatt();
        $this->setRabattActive($this->createTestRabatt());
    }

    public function tearDown(): void {
        // order is important:
        $this->setRabattInactive($this->createTestRabatt());
        $this->tearDownRabatt();
        parent::tearDown();
    }

    /**
     * @var Rabatt
     */
    protected $rabatt;

    /**
     * @test
     */
    function it_retrieves_the_first_active_rabatt() {
        $active = app( RabattRepository::class )->active();
        $this->assertEquals( 'Testrabatt A', $active->first()->title );
    }


}
