<?php

namespace Tests\Unit;

use App\Exceptions\BookingException;
use App\Factories\AngebotFactory;
use App\Factories\AppartementFactory;
use App\Factories\PferdepensionFactory;
use App\Models\Angebot;
use App\Models\Appartement;
use App\Models\Fitness;
use App\Models\Pferdepension;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\Concerns\InteractsWithDatabase;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\CreatesModels;
use Tests\TestCase;
use Tests\DBSwitcher;

class VeranstaltungTest extends TestCase {

    use DBSwitcher, CreatesModels, DatabaseMigrations, InteractsWithDatabase;

    /**
     * @var Angebot|null
     */
    public $model = null;


    public function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->model = $this->createTestveranstaltung();
    }

    /**
     * @test
     */
    public function an_angebot_has_a_start_date() {
        $start = new Carbon('8.10.2020');
        $this->assertEquals( $start, $this->model->startdate );
    }

    /**
     * @test
     */
    public function an_angebot_has_an_enddate() {
        $start = new Carbon('11.10.2020');
        $this->assertEquals( $start, $this->model->enddate );
    }


}
